set( APPLICATION_NAME       		"SyncAccount" )
set( APPLICATION_SHORTNAME  		"desktopsync" )
set( APPLICATION_EXECUTABLE 		"desktopsync" )
set( APPLICATION_DOMAIN     		"syncaccount.com" )
set( APPLICATION_VENDOR     		"SyncAccount" )
set( APPLICATION_UPDATE_URL 		"https://updates.syncaccount.com/cloud/" CACHE string "URL for updater" )
set( APPLICATION_SYNC_URL 			"https://democloud.syncaccount.com/" CACHE string "url for sync" )
set( APPLICATION_HELP_URL 			"http://docs.syncaccount.com/docs/%1.%2/" CACHE string "url for help" )

set( THEME_CLASS            		"myCloudTheme" )
set( APPLICATION_CONFIG_FILE        "desktopsync.cfg" )
set( APPLICATION_TRAYFOLDER_ICON    "desktopsync-icon" )
set( APPLICATION_APP_ICON   		"desktopsync-icon" )
set( APPLICATION_REV_DOMAIN 		"com.syncaccount.desktopclient" )
set( WIN_SETUP_BITMAP_PATH  		"${OEM_THEME_DIR}/nsi" )
set( THEME_INCLUDE          		"${OEM_THEME_DIR}/mytheme.h" )
set( APPLICATION_WIZARD_TITLE_COLOR "#ffffff" )
set( APPLICATION_HEADER_BG_COLOR 	"#ffffff" )
# set( APPLICATION_LICENSE   		"${OEM_THEME_DIR}/license.txt )
